apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-sqlserver
  template:
    metadata:
      labels:
        app: payments-sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Payments!Passw0rd"
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-sqlserver
spec:
  selector:
    app: payments-sqlserver
  ports:
  - port: 1433
    targetPort: 1433
